export const STEP_TO_ONE ="STEP_TO_ONE";
export const PRODUCT_TO_ONE ="PRODUCT_TO_ONE";

// 系统菜单
export const SYS_SUBMENU_GET = "SYS_SUBMENU_GET"; 
export const SYS_SUBMENU_SET = "SYS_SUBMENU_SET";
export const SYS_SUBMENU_CLEAR = "SYS_SUBMENU_CLEAR"; 

// 路由侧边栏
export const ROUTE_SUBMENU_SET = "ROUTE_SUBMENU_SET";
export const ROUTE_SUBMENU_GET = "ROUTE_SUBMENU_GET";
export const ROUTE_SUBMENU_MAIN_SET = "ROUTE_SUBMENU_MAIN_SET";
export const ROUTE_SUBMENU_MAIN_GET = "ROUTE_SUBMENU_MAIN_GET";